---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: observability
  namespace: argocd
spec:
  description: "Observability project"
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-lgtma-stack
  namespace: argocd
spec:
  project: observability
  source:
    chart: lgtm-distributed
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.1.0
    helm:
      releaseName: lgtm-distributed
  destination:
    server: "https://kubernetes.default.svc"
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: false 